force-app/main/default/objects/Account/fields/Registration_Number__c.field-meta.xml
<CustomField>
    <fullName>Registration_Number__c</fullName>
    <description>A unique identifier for each patient</description>
    <label>Registration Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Medical_Record__c/Medical_Record__c.object-meta.xml
<CustomObject>
    <label>Medical Record</label>
    <nameField>
        <displayFormat>MR-{000000}</displayFormat>
        <label>Medical Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Medical Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Medical_Record__c/fields/Is_Ongoing_Treatment__c.field-meta.xml
<CustomField>
    <fullName>Is_Ongoing_Treatment__c</fullName>
    <defaultValue>false</defaultValue>
    <description>The field is used to mark if a medical record has a ongoing treatment</description>
    <label>Is Ongoing Treatment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Medical_Record__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <label>Patient</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Medical Records</relationshipLabel>
    <relationshipName>Medical_Records</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/classes/MedicalRecordFlexController.cls
public without sharing class MedicalRecordFlexController{
    @InvocableMethod
    public static List<Response> getMedicalRecords(List<Request> requests) {
        system.debug('request**********'+requests);
        Request input = requests[0];
        List<Response> responses = new List<Response>();
        Response output = new Response();
        responses.add(output);
        List<Medical_Record__c> medicalRecordList = [Select Id, Procedure_Date__c, Procedure_Name__c, Patient__r.Registration_Number__c,Is_Ongoing_Treatment__c, Notes__c FROM Medical_Record__c WHERE Patient__r.Registration_Number__c =: input.registrationNumber];
        output.Prompt = 'Following are the medical records of the patient that should be considered during FAQs';
        for(Medical_Record__c medRecord: medicalRecordList){
            output.Prompt += '\nProcedure Date: '+medRecord.Procedure_Date__c;
            output.Prompt += '\nProcedure Name: '+medRecord.Procedure_Name__c;
            output.Prompt += '\nIs the condition ongoing?: '+medRecord.Is_Ongoing_Treatment__c;
            output.Prompt += '\nNotes: '+medRecord.Notes__c;
            output.Prompt += '**********************************';
        }
        

        return responses;
    }
 
    // Type and API Name of all variables must match the template
    public class Request {
        @InvocableVariable(required=true)
        public String registrationNumber;
    }

    public class Response {
        @InvocableVariable
        public String Prompt;
    }
}